name: CI
on:
  push:
    branches: [ master ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm ci
      - run: npm run lint
